# Generated by Django 4.2.30 on 2026-09-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('oud', 'OUD Malikee'), ('mamool', 'Mamool Incense'), ('bakhoor', 'Bakhoor')], max_length=20)),
                ('fragrance_family', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(max_length=500)),
                ('badge', models.CharField(blank=True, choices=[('', 'No Badge'), ('bestseller', 'Bestseller'), ('new', 'New'), ('sold_out', 'Sold Out')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
