# Generated by Django 4.2.30 on 2026-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longevity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
