# Generated by Django 4.2.30 on 2026-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
