# Generated by Django 4.2.30 on 2026-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_top_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
