# Generated by Django 4.2.30 on 2026-09-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
