# Generated by Django 4.2.30 on 2026-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_cartitem_cart_remove_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('inside_sylhet', 'Inside Sylhet City'), ('outside_sylhet', 'Outside Sylhet'), ('dhaka_city', 'Dhaka City'), ('outside_dhaka', 'Outside Dhaka')], max_length=30, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
